apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokto-frontend  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dokto-frontend
  template:
    metadata:
      labels:
        app: dokto-frontend
    spec:
      containers:
      - name: dokto-frontend
        image: dokto.azurecr.io/toybethsystems/dokto-frontend:{{imagetag}}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5       
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5    
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 10
