apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokto-frontend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokto-frontend
  template:
    metadata:
      labels:
        app: dokto-frontend
    spec:
      containers:
      - name: dokto-frontend
        image: dokto.azurecr.io/toybethsystems/dokto-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        livenessProbe:
          exec:
          command:
            - /opt/liveness.sh
          periodSeconds: 300
          timeoutSeconds: 300
          successThreshold: 1
          failureThreshold: 5       
        readinessProbe:
          exec:
          command:
            - /opt/readiness.sh
          periodSeconds: 300
          timeoutSeconds: 300
          successThreshold: 1
          failureThreshold: 5    
        startupProbe:
          exec:
          command:
            - /opt/liveness.sh
          periodSeconds: 300
          timeoutSeconds: 300
          failureThreshold: 90
        
